<!-- Author: Peter Gorban (GitHub: https://github.com/msifd) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scs</string>
	</array>
	<key>name</key>
	<string>SCs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#illegal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identificator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#braces</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#contour</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>braces</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\{|\}|\(\*|\*\)</string>
					<key>name</key>
					<string>keyword.operator.brace</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\/\/.*$</string>
					<key>name</key>
					<string>comment.line</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\/\*</string>
					<key>end</key>
					<string>\*\/</string>
					<key>name</key>
					<string>comment.block</string>
				</dict>
			</array>
		</dict>
		<key>contour</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\[\*|\*\]</string>
					<key>name</key>
					<string>string</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>name</key>
					<string>string</string>
				</dict>
			</array>
		</dict>
		<key>identificator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.{3}</string>
					<key>name</key>
					<string>entity.other</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.{0,2}\w+:</string>
					<key>name</key>
					<string>support.type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.{0,2}\w+</string>
					<key>name</key>
					<string>entity.name</string>
				</dict>
			</array>
		</dict>
		<key>illegal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.{3}\w+:?</string>
					<key>name</key>
					<string>invalid.illegal</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;|;;</string>
					<key>name</key>
					<string>keyword.operator.break</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\=</string>
					<key>name</key>
					<string>keyword.operator.set</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&lt;-|-&gt;|&lt;=|=&gt;|==</string>
					<key>name</key>
					<string>keyword.operator.arrow</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.scs</string>
	<key>uuid</key>
	<string>176582b3-63d4-4dfb-b2ba-63984f935d9e</string>
</dict>
</plist>